CREATE TABLE STOCK_DETAILS (
    ID INT AUTO_INCREMENT  PRIMARY KEY,
    SYMBOL VARCHAR(25) NOT NULL,
    BID_PRICE VARCHAR(10) NOT NULL,
    ASK_PRICE VARCHAR(10) NOT NULL,
    EVENT_DATE DATE NOT NULL
);